---
- hosts: all
  become: yes
  roles:
    - hardening

- hosts: masters
  become: yes
  vars:
    is_master: true
  roles:
    - k3s

- hosts: workers
  become: yes
  vars:
    is_master: false
    k3s_server_url: "{{ hostvars[ groups['masters'][0] ].k3s_server_url }}"
    k3s_token: "{{ hostvars[ groups['masters'][0] ].k3s_token }}"
  roles:
    - k3s
