---
# Run this playbook after user-setup; it hardens the system

- name: Disable root bash history
  lineinfile:
    path: /root/.bashrc
    line: "HISTFILESIZE=0"
    state: present

- name: Clear root bash history
  shell: "dd if=/dev/null of=/root/.bash_history"

- name: Disable root login
  user:
    name: root
    password_lock: true

- name: Disable homelab user bash history
  lineinfile:
    path: /home/{{ defaultUser }}/.bashrc
    line: "HISTFILESIZE=0"
    state: present

- name: Remove bash history size
  lineinfile:
    path: /home/{{ defaultUser }}/.bashrc
    regexp: "^HISTSIZE.*$"
    state: absent

- name: Remove bash history file size
  lineinfile:
    path: '/home/{{ defaultUser }}/.bashrc'
    regexp: '^(.*)HISTFILESIZE(.*)$'
    line: 'HISTFILESIZE=0'

# TODO: ensure root SSH login is disabled

- name: Clear bash history
  shell: 'dd if=/dev/null of=/home/{{ defaultUser }}/.bashrc'

- name: Disable password authentication
  lineinfile:
    path: '/etc/ssh/sshd_config'
    regexp: '^(.*)PasswordAuthentication(.*)$'
    line: 'PasswordAuthentication no'

- name: Disable IPv6
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: "1"
    state: "present"
    reload: "yes"
  with_items:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6
    - net.ipv6.conf.lo.disable_ipv6

- name: Disable IPv6 in /etc/sysctl.conf
  ansible.builtin.lineinfile:
    path: "/etc/sysctl.conf"
    line: "{{ item }}=1"
    state: "present"
  with_items:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6
    - net.ipv6.conf.lo.disable_ipv6

- name: Install firewalld
  ansible.builtin.package:
    name: firewalld
    state: present

- name: Create MGMT zone
  ansible.posix.firewalld:
    zone: "mgmt"
    state: "present"
    permanent: true

- name: Add MGMT interface to new zone
  ansible.posix.firewalld:
    zone: "mgmt"
    interface: "{{ mgmtInterface }}"
    permanent: true
    state: enabled

- name: Enable ssh for mgmt
  ansible.posix.firewalld:
    zone: "mgmt"
    service: ssh
    permanent: true
    state: enabled

- name: Enable ICMP on mgmt
  block:
  - ansible.posix.firewalld:
      zone: "mgmt"
      state: enabled
      permanent: true
      icmp_block_inversion: true

  - ansible.posix.firewalld:
      zone: "mgmt"
      state: enabled
      permanent: true
      icmp_block: echo-request

  - ansible.posix.firewalld:
      zone: "mgmt"
      state: enabled
      permanent: true
      icmp_block: echo-reply

  - name: "Default DROP on mgmt"
    ansible.posix.firewalld:
      zone: "mgmt"
      state: present
      permanent: true
      target: DROP

- name: Disable ssh for public
  ansible.posix.firewalld:
    zone: "public"
    service: ssh
    permanent: true
    state: disabled

- name: Reload firewalld
  ansible.builtin.service:
    name: firewalld
    state: reloaded
