---
# Run this playbook after user-setup; it hardens the system

- name: Disable root bash history
  lineinfile:
    path: /root/.bashrc
    line: "HISTFILESIZE=0"
    state: present

- name: Clear root bash history
  shell: "dd if=/dev/null of=/root/.bash_history"

- name: Disable root login
  user:
    name: root
    password_lock: true

- name: Disable homelab user bash history
  lineinfile:
    path: /home/{{ defaultUser }}/.bashrc
    line: "HISTFILESIZE=0"
    state: present

- name: Remove bash history size
  lineinfile:
    path: /home/{{ defaultUser }}/.bashrc
    regexp: "^HISTSIZE.*$"
    state: absent

- name: Remove bash history file size
  lineinfile:
    path: '/home/{{ defaultUser }}/.bashrc'
    regexp: '^(.*)HISTFILESIZE(.*)$'
    line: 'HISTFILESIZE=0'

# TODO: ensure root SSH login is disabled

- name: Clear bash history
  shell: 'dd if=/dev/null of=/home/{{ defaultUser }}/.bashrc'

- name: Disable password authentication
  lineinfile:
    path: '/etc/ssh/sshd_config'
    regexp: '^(.*)PasswordAuthentication(.*)$'
    line: 'PasswordAuthentication no'

- name: Disable IPv6
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: "1"
    state: "present"
    reload: "yes"
  with_items:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6
    - net.ipv6.conf.lo.disable_ipv6

- name: Disable IPv6 in /etc/sysctl.conf
  ansible.builtin.lineinfile:
    path: "/etc/sysctl.conf"
    line: "{{ item }}=1"
    state: "present"
  with_items:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6
    - net.ipv6.conf.lo.disable_ipv6

- name: Install iptables
  ansible.builtin.package:
    name: iptables
    state: present

- name: Install iptables-persistent
  ansible.builtin.package:
    name: iptables-services
    state: present

- name: Allow loopback traffic
  ansible.builtin.iptables:
    chain: INPUT
    in_interface: lo
    jump: ACCEPT

- name: Allow related and established connections
  ansible.builtin.iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT

- name: Allow SSH on mgmt
  ansible.builtin.iptables:
    chain: INPUT
    in_interface: "{{ mgmtInterface }}"
    protocol: tcp
    destination_port: 22
    jump: ACCEPT

- name: Don't forward traffic from MGMT to LAN
  ansible.builtin.iptables:
    chain: FORWARD
    in_interface: "{{ mgmtInterface }}"
    out_interface: "{{ egressInterface }}"
    protocol: tcp
    destination_port: 22
    jump: DROP

- name: Don't forward traffic from LAN to MGMT
  ansible.builtin.iptables:
    chain: FORWARD
    in_interface: "{{ egressInterface }}"
    out_interface: "{{ mgmtInterface }}"
    protocol: tcp
    destination_port: 22
    jump: DROP

- name: Deny everything else
  ansible.builtin.iptables:
    chain: INPUT
    policy: DROP

- name: Save iptables rules
  community.general.iptables_state:
    state: saved
    path: /etc/iptables/rules.v4
