---
# Role metadata
galaxy_info:
  author: justinschw
  description: Configure Proxmox provisioner user for Packer and Terraform
  license: MIT
  min_ansible_version: 2.9

  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm

  galaxy_tags:
    - proxmox
    - automation
    - infrastructure
    - packer
    - terraform

dependencies: []
