- name: Allow 6443
  ansible.posix.firewalld:
    zone: "mgmt"
    port: 6443/tcp
    permanent: true
    state: enabled

- name: Allow 10250
  ansible.posix.firewalld:
    zone: "mgmt"
    port: 10250/tcp
    permanent: true
    state: enabled


- name: Reload firewalld
  ansible.builtin.service:
    name: firewalld
    state: reloaded

- name: Check if kubectl is installed
  stat:
    path: /usr/local/bin/kubectl
  register: kubectl_exe

- name: Install curl
  ansible.builtin.package:
    name: curl
    state: present
    update_cache: true

- name: Download k3s install script
  ansible.builtin.get_url:
    url: https://get.k3s.io
    dest: /tmp/k3s-install.sh
    mode: u=xwr,g=xr,o=xr
  when: kubectl_exe.stat.exists == False

- name: Run install script
  shell: "INSTALL_K3S_EXEC='server --bind-address {{ assignedMgmtIp }} --advertise-address {{ assignedMgmtIp }} --node-name {{ assignedHostname }} --node-ip {{ assignedMgmtIp }} --node-external-ip {{ assignedMgmtIp }} --tls-san {{ assignedMgmtIp }} --cluster-init' /tmp/k3s-install.sh || true"
  when: kubectl_exe.stat.exists == False

- name: create kubeconfig dir for default user
  file:
    path: /home/{{ defaultUser }}/.kube
    state: directory

- name: Setup kubeconfig for default user
  shell: "cp /etc/rancher/k3s/k3s.yaml /home/{{ defaultUser }}/.kube/config"

- name: Change file ownership, group and permissions
  ansible.builtin.file:
    path: /home/{{ defaultUser }}/.kube/config
    owner: "{{ defaultUser }}"
    group: "{{ defaultUser }}"
    mode: 'u=rw'

- name: Set KUBECONFIG for default user
  lineinfile:
    path: /home/{{ defaultUser }}/.bashrc
    line: "export KUBECONFIG=$HOME/.kube/config"
    state: present
