- name: Check if kubectl is installed
  stat:
    path: /usr/local/bin/k3s
  register: k3s_exe

- name: Install curl
  ansible.builtin.package:
    name: curl
    state: present
    update_cache: true

- name: Download k3s install script
  ansible.builtin.get_url:
    url: https://get.k3s.io
    dest: /tmp/k3s-install.sh
    mode: u=xwr,g=xr,o=xr
  when: k3s_exe.stat.exists == False

- name: Install as server (master)
  shell: >
    INSTALL_K3S_EXEC='server --bind-address {{ listenAddress }}
    --advertise-address {{ master_internal_ip | split('/') | first }}
    --node-name {{ inventory_hostname }}
    --node-ip {{ master_internal_ip | split('/') | first }}
    --tls-san {{ master_hostname }}
    --cluster-init' /tmp/k3s-install.sh || true
  when: (is_master | default(false)) and k3s_exe.stat.exists == False

- name: Fail if worker lacks server info
  ansible.builtin.fail:
    msg: "k3s_server_url and k3s_token must be set for worker nodes"
  when: not (is_master | default(false)) and (k3s_server_url is not defined or k3s_token is not defined)

- name: Install as agent (worker)
  shell: >
    INSTALL_K3S_EXEC='agent --server {{ k3s_server_url }}
    --token {{ k3s_token }}
    --node-name {{ inventory_hostname }}
    --node-external-ip {{ master_internal_ip | split('/') | first }}' /tmp/k3s-install.sh || true
  when: not (is_master | default(false)) and k3s_exe.stat.exists == False

- name: Read k3s node token (server)
  ansible.builtin.slurp:
    src: /var/lib/rancher/k3s/server/node-token
  register: k3s_token_raw
  when: is_master | default(false)

- name: Set `k3s_server_url` and `k3s_token` facts (cacheable)
  ansible.builtin.set_fact:
    k3s_server_url: "https://{{ master_hostname }}:6443"
    k3s_token: "{{ (k3s_token_raw.content | b64decode).strip() }}"
    cacheable: yes
  run_once: true
  delegate_to: "{{ groups['masters'][0] }}"
  when: is_master | default(false)

- name: Update kubeconfig with correct server address
  ansible.builtin.command:
    cmd: >
      sed -i 's|https://[0-9a-zA-Z.-]*:6443|{{ k3s_server_url }}|g' {{ kubeConfigPath }}
  when: is_master | default(false)

- name: Read kube config
  ansible.builtin.slurp:
    src: "{{ kubeConfigPath }}"
  register: k3s_kubeconfig_raw
  when: is_master | default(false)

- name: Set `k3s_kubeconfig` fact (cacheable)
  ansible.builtin.set_fact:
    k3s_kubeconfig: "{{ k3s_kubeconfig_raw.content | b64decode }}"
    cacheable: yes
  run_once: true
  delegate_to: "{{ groups['masters'][0] }}"
  when: is_master | default(false)

- name: Upload kubeconfig to S3
  aws_s3:
    aws_access_key: "{{ s3_access_key }}"
    aws_secret_key: "{{ s3_secret_key }}"
    endpoint_url: "{{ s3_endpoint }}"
    region: "{{ s3_region }}"
    bucket: "{{ s3_bucket_name }}"
    object: "{{ cluster_name }}/kubeconfig.yaml"
    mode: put
    content: "{{ k3s_kubeconfig }}"
  when: is_master | default(false)
