---
- name: Install java
  ansible.builtin.package:
    name: java
    state: present

- name: Download Jenkins repo
  ansible.builtin.get_url:
    url: "{{ jenkinsRepoUrl }}"
    dest: /etc/yum.repos.d/jenkins.repo

- name: Install Jenkins repo key
  rpm_key:
    state: present
    key: "{{ jenkinsRepoKeyUrl }}"

- name: Install Jenkins
  ansible.builtin.package:
    name: jenkins
    state: present
    update_cache: true

# TODO: https
- name: Enable Jenkins access from MGMT
  ansible.posix.firewalld:
    zone: "mgmt"
    port: 8080
    permanent: true
    state: enabled
