---
galaxy_info:
  author: "maintainer"
  description: "Role to install self-managed GitLab CE"
  company: ""
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Debian
      versions:
        - buster
        - bullseye
        - bookworm
    - name: Ubuntu
      versions:
        - bionic
        - focal
        - jammy
dependencies: []
